approvedGitRepositories:
  - '**'

compressionLevel: 0

defaultSemverRangePrefix: ''

enableGlobalCache: true

enableScripts: true

# Make sure each workspace has its own local node_modules
# This greatly limit dependency leaking between modules
nmHoistingLimits: workspaces

# Use hardlinks to a global cache
nmMode: hardlinks-local

# Keep old-school saving of dependencies in node_modules
# This makes debugging imported modules so much easier
nodeLinker: node-modules

npmMinimalAgeGate: 0
